# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-20 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facultades', '0001_initial'),
        ('ubigeo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('direccion', models.CharField(max_length=254)),
                ('telefono', models.CharField(max_length=9)),
                ('correo', models.EmailField(max_length=254)),
                ('direccion_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubigeo.Departamento')),
                ('direccion_distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubigeo.Distrito')),
                ('direccion_provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubigeo.Provincia')),
            ],
        ),
        migrations.CreateModel(
            name='EstudianteEAP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha fin')),
                ('eap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facultades.EAP')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante_eaps', to='estudiantes.Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='EstudianteGrado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante_grados', to='estudiantes.Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254)),
                ('codigo', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='estudiantegrado',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='estudiantes.Grado'),
        ),
    ]
