# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-21 01:42
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='direccion_distrito',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='direccion_provincia', chained_model_field='provincia', on_delete=django.db.models.deletion.CASCADE, to='ubigeo.Distrito'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='direccion_provincia',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='direccion_departamento', chained_model_field='departamento', on_delete=django.db.models.deletion.CASCADE, to='ubigeo.Provincia'),
        ),
    ]
